apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pale-2
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  vault:
    enabled: true
    paths:
      - kvPath: /azuread/data/dev/creds/pale-2
        mountPath: /secrets/azuread/pale-2
      - kvPath: /kv/preprod/fss/pale-2/default
        mountPath: /secrets/default
      - kvPath: serviceuser/data/dev/srvpale2
        mountPath: /secrets/serviceuser
  webproxy: true
  ingresses:
    - "https://pale-2.nais.preprod.local"
  env:
    - name: MQ_INPUT_QUEUE_NAME
      value: QA.Q1_PALE.INPUT
    - name: MQ_HOST_NAME
      value: b27apvl177.preprod.local
    - name: MQ_PORT
      value: '1413'
    - name: MQ_GATEWAY_NAME
      value: MQ1LSC04
    - name: MQ_CHANNEL_NAME
      value: Q1_PALE_2
    - name: MQ_APPREC_QUEUE_NAME
      value: QA.Q414.IU03_UTSENDING
    - name: MQ_INPUT_BOQ_QUEUE_NAME
      value: Q1_PALE_2.INPUT_BOQ
    - name: AKTOR_REGISTER_V1_URL
      value: https://app-q1.adeo.no/aktoerregister/api/v1
    - name: SECURITY_TOKEN_SERVICE_URL
      value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
    - name: ARENA_OUTBOUND_QUEUENAME
      value: QA.Q1_414.FS06_ARENA
    - name: NORG2_V1_ENDPOINT_URL
      value: https://app-q1.adeo.no/norg2/api/v1
    - name: PERSON_V3_ENDPOINT_URL
      value: https://wasapp-q1.adeo.no/tpsws/ws/Person/v3
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: SUBSCRIPTION_ENDPOINT_URL
      value: https://wasapp-q1.adeo.no/nav-emottak-eletter-web/services/