apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pale-2
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  vault:
    enabled: true
  env:
    - name: MQ_INPUT_QUEUE_NAME
      value: QA.P_PALE.INPUT
    - name: MQ_HOST_NAME
      value: a01apvl064.adeo.no
    - name: MQ_PORT
      value: '1414'
    - name: MQ_GATEWAY_NAME
      value: MPLSC04
    - name: MQ_CHANNEL_NAME
      value: P_PALE_2
    - name: MQ_APPREC_QUEUE_NAME
      value: QA.Q414.IU03_UTSENDING
    - name: MQ_INPUT_BOQ_QUEUE_NAME
      value: P_PALE-2.INPUT_BOQ
    - name: MQ_GATEWAY_NAME
      value: MPLSC04
    - name: MQ_CHANNEL_NAME
      value: P_PALE-2
    - name: AKTOR_REGISTER_V1_URL
      value: https://app.adeo.no/aktoerregister/api/v1
    - name: SECURITY_TOKEN_SERVICE_URL
      value: https://sts.adeo.no/SecurityTokenServiceProvider/
    - name: HELSEPERSONELL_V1_ENDPOINT_URL
      value: https://pep-gw.oera.no:9443/samhandler/helse/helsepersonell/v1
    - name: DOK_ARKIV_URL
      value: http://dokarkiv/rest/journalpostapi/v1/journalpost
    - name: ARENA_OUTBOUND_QUEUENAME
      value: QA.P_414.FS06_ARENA
    - name: NORG2_V1_ENDPOINT_URL
      value: https://app.adeo.no/norg2/ws/Arbeidsfordeling/v1
    - name: ARBEIDSFORDELING_V1_ENDPOINT_URL
      value: https://app.adeo.no/norg2/ws/Arbeidsfordeling/v1
    - name: PERSON_V3_ENDPOINT_URL
      value: https://wasapp.adeo.no/tpsws/ws/Person/v3
    - name: DISKRESJONSKODE_ENDPOINT_URL
      value: https://wasapp.adeo.no/tpsws/Diskresjonskode