apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pale-2
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 768Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/srvpale2
        mountPath: /secrets/serviceuser
      - kvPath: /kv/prod/fss/pale-2/teamsykmelding
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
  envFrom:
    - secret: pale-2-redis-password
  ingresses:
    - "https://pale-2.nais.adeo.no"
  env:
    - name: MQ_INPUT_QUEUE_NAME
      value: QA.P_PALE.INPUT
    - name: MQ_HOST_NAME
      value: a01apvl271.adeo.no
    - name: MQ_PORT
      value: '1414'
    - name: MQ_GATEWAY_NAME
      value: MPLS04
    - name: MQ_CHANNEL_NAME
      value: P_PALE_2
    - name: MQ_APPREC_QUEUE_NAME
      value: QA.P414.IU03_UTSENDING
    - name: MQ_INPUT_BOQ_QUEUE_NAME
      value: QA.P_PALE_2.INPUT_BOQ
    - name: ARENA_OUTBOUND_QUEUENAME
      value: QA.P414.FS06_ARENA
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SASL_SSL://a01apvl00145.adeo.no:8443,SASL_SSL://a01apvl00146.adeo.no:8443,SASL_SSL://a01apvl00147.adeo.no:8443,SASL_SSL://a01apvl00149.adeo.no:8443
    - name: SUBSCRIPTION_ENDPOINT_URL
      value: https://wasapp.adeo.no/nav-emottak-eletter-web/services/
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.adeo.no/graphql
    - name: PALE_2_REGLER_ENDPOINT_URL
      value: https://pale-2-regler.nais.adeo.no
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: PALE_VEDLEGG_BUCKET_NAME
      value: teamsykmelding-pale2-vedlegg-bucket-prod